TIMEOUT = object()
NOT_FOUND = object()
STALE_WHILE_REVALIDATE = "STALE_WHILE_REVALIDATE"
NETWORK_FIRST = "NETWORK_FIRST"
NO_CACHE = "NO_CACHE"
CACHE_FIRST = "CACHE_FIRST"

LAYOUTS = "LAYOUTS"
TEMPLATE_WITH_CONTENT_PANEL = "TEMPLATE_WITH_CONTENT_PANEL"
